In [ ]:
A=[8,6,7,12,3,5] #list sort
A.sort()
print(A)

[3, 5, 6, 7, 8, 12]


In [ ]:
a=(12,3,45,7)
b=sorted(a)     #tuple sorted
print(a)
print(b)

(12, 3, 45, 7)
[3, 7, 12, 45]


In [ ]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.linspace(1,13,15).reshape(5,3)
print(a)


[[ 1.          1.85714286  2.71428571]
 [ 3.57142857  4.42857143  5.28571429]
 [ 6.14285714  7.          7.85714286]
 [ 8.71428571  9.57142857 10.42857143]
 [11.28571429 12.14285714 13.        ]]


In [ ]:
b=np.array([3,6,7,8,89,45]).reshape(2,1,3)#
print(b)

[[[ 3  6  7]]

 [[ 8 89 45]]]


In [ ]:
c=np.array([3,7,5,9,3,6])
c.resize(2,1,3)#change
print(c)

[[[3 7 5]]

 [[9 3 6]]]


In [ ]:
a=np.array([3,6,78,8,9,7,8])
b=np.array([1,3,4,2,5,6,6])
print(a-b)      #sub
print(a+b)#mul

[ 2  3 74  6  4  1  2]
[ 4  9 82 10 14 13 14]


In [ ]:
a=np.array([3,6,7,1]).reshape(2,2)
b=np.array([[3,4,4,4]]).reshape(2,2)
print(a)
print("###########")
print(b)
c=a*b               #one one elenent multyply
print("########")
print(c)



[[3 6]
 [7 1]]
###########
[[3 4]
 [4 4]]
########
[[ 9 24]
 [28  4]]


In [ ]:
a=np.array([3,6,7,1]).reshape(2,2)
b=np.array([[3,4,4,4]]).reshape(2,2)
print(a)
print("###########")
print(b)
c=a.dot(b)              #matrix multyplication
print("########")
print(c)



[[3 6]
 [7 1]]
###########
[[3 4]
 [4 4]]
########
[[33 36]
 [25 32]]


In [ ]:
a=np.array([3,6,7,1]).reshape(2,2)
print(a)
print("########")
print(a.max(axis=0))              #max ele in colum
print("########")                 #max elein row
print(a.max(axis=1))




[[3 6]
 [7 1]]
########
[7 6]
########
[6 7]


In [ ]:
a=np.array([3,5,7,9,8])
print(a.max())          #max ele print
print(a.min())          #min ele print

9
3


In [ ]:
a=np.array([3,6,7,1]).reshape(2,2)
print(a)
print("########")
print(a.min(axis=0))              #min ele in colum
print("########")                 #min elein row
print(a.min(axis=1))




[[3 6]
 [7 1]]
########
[3 1]
########
[3 1]


In [ ]:
a=np.array([2,4,5,6,7,8]).reshape(2,1,3)
b=np.array([3,5,8,9,5,3]).reshape(2,1,3)
print(a)
print("%%%%%%%")
print(b)
print("&&&&&&")
print("after vertically stacking the array!") #vstack axis=0
print(np.vstack((a,b)))

[[[2 4 5]]

 [[6 7 8]]]
%%%%%%%
[[[3 5 8]]

 [[9 5 3]]]
&&&&&&
after vertically stacking the array!
[[[2 4 5]]

 [[6 7 8]]

 [[3 5 8]]

 [[9 5 3]]]


In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")        #spliting array equal parts of the array
np.vsplit(a,3)                  #vertical array print rows


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")        #spliting arrays check the index and ex: 2:0,1 arrays print
                                          # ex:3:0,1,2(0,1 already print so 2 array only print)
np.vsplit(a,(2,3))                        #print rows


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")        #spliting horizantal arrays check the index and ex: 2:0,1 arrays print
                                          # ex:3:0,1,2(0,1 already print so 2 array only print)
np.hsplit(a,(3,2))                            #print colums(stright)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(6, 0), dtype=int64),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
a=np.array([3,4,6,7]).reshape(2,2,1)
print(a)
print(a.argmax())             #print  index of the max ele in the array

[[[3]
  [4]]

 [[6]
  [7]]]
3


In [ ]:
a=np.array([3,4,6,7]).reshape(2,2,1)
print(a)
print(a.argmin())             #print  index of the min ele in the array

[[[3]
  [4]]

 [[6]
  [7]]]
0


In [ ]:
a=np.array([3,4,6,7,5,7,4,6,4]).reshape(3,3)
print(a)
print(a.argmax(axis=0))             #print  index of the max ele in the array
                                      #and print colum of the max ele

[[3 4 6]
 [7 5 7]
 [4 6 4]]
[1 2 1]


In [ ]:
a=np.array([3,4,6,7,5,7,4,6,4]).reshape(3,3)
print(a)
print(a.argmax(axis=1))             #print  index of the max ele in the array
                                      #and print row of the max ele

[[3 4 6]
 [7 5 7]
 [4 6 4]]
[2 0 1]


In [ ]:
a=np.array([3,4,6,7,5,7,4,6,4]).reshape(3,3)
print(a)
print(a.argmin(axis=0))             #print  index of the min ele in the array
                                      #and print row of the min ele

[[3 4 6]
 [7 5 7]
 [4 6 4]]
[0 0 2]


In [ ]:
a=np.array([3,4,6,7,5,7,4,6,4]).reshape(3,3)
print(a)
print(a.argmin(axis=1))             #print  index of the min ele in the array
                                      #and print row of the min ele

[[3 4 6]
 [7 5 7]
 [4 6 4]]
[0 1 0]


In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")

np.hsplit(a,(3))                            #print  horizantal colums(stright)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
a=np.array([2,4,5,6,7,8]).reshape(2,1,3)
b=np.array([3,5,8,9,5,3]).reshape(2,1,3)
print(a)
print("%%%%%%%")
print(b)
print("&&&&&&")
print("after horizantally stacking the array!")             #hstact axis=1
                                                           # a attech the array of b array
print(np.hstack((a,b)))

[[[2 4 5]]

 [[6 7 8]]]
%%%%%%%
[[[3 5 8]]

 [[9 5 3]]]
&&&&&&
after horizantally stacking the array!
[[[2 4 5]
  [3 5 8]]

 [[6 7 8]
  [9 5 3]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("after dstack")
print(np.dstack(a))       #dstack 2,3,5(group,row,colum)
                            #3,5,2(gropu,row,colum)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


STATISTICS:

In [ ]:
#statistics
#mean,medium,std.var



TRIGNOMENTRY:

In [ ]:
a=np.pi
print(a)          #radians

3.141592653589793


In [ ]:
np.rad2deg(a)


180.0

In [ ]:
a=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(a)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
a=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])

print(np.rad2deg(a))            #radiance covert to deg

[ 45.  60.  90. 180.]


In [ ]:
b=np.array([30,45,60,90,120,180])
c=np.deg2rad(b)                     #deg to convert radiance
print(c)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
b=np.array([0,30,45,60,90,120,180])
np.sin(b)


array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
b=np.array([0,30,45,60,90,120,180])
np.cos(b)


array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
b=np.array([0,30,45,60,90,120,180])
np.tan(b)


array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arccos(1)  #cos^-1


0.0

In [ ]:
np.arcsin(1)    #sin^-1

1.5707963267948966

In [ ]:
np.arctan(1)              #tan^-1

0.7853981633974483

In [ ]:
a=8
b=6                                       #print hypot
print(np.hypot(a,b))

10.0


In [ ]:
a=np.array([90,3,45,21,34,90,21])
print(np.where(a==21))              #a==21 present at 21 print only that inddex


(array([3, 6]),)


In [ ]:
a=np.array([90,3,45,21,34,90,21])
print(np.where(a%2==0))              # print only even numbers  that inddex


(array([0, 4, 5]),)


In [ ]:
a=np.array([90,3,45,21,34,90,21])
print(np.where(a>25))              #print above 25 valus print only that inddex


(array([0, 2, 4, 5]),)


In [ ]:
import numpy as np

In [ ]:
a=np.array([2,4,7,9,12,98])
print(np.searchsorted(a,9)) `#take a sorted list defined element and display inde of the ele

3


LINEAR ALGEBRA AND UFUNC:

In [ ]:
a=np.array([2,4,7,8,9])
b=np.array([4,8,2,9,6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.divmod(a,b))
print(np.mod(a,b))




[ 6 12  9 17 15]
[-2 -4  5 -1  3]
[0.5        0.5        3.5        0.88888889 1.5       ]
(array([0, 0, 3, 0, 1]), array([2, 4, 1, 8, 3]))
[2 4 1 8 3]


In [ ]:
sort:

SETS FUNCTIONS:

In [ ]:
a=np.array([2,5,7,8,])
b=np.array([3,6,8,9,33])  #union
print(np.union1d(a,b))

[ 2  3  5  6  7  8  9 33]


In [ ]:
a=np.array([2,5,7,8,])
b=np.array([3,6,8,9,33])  #intersection
print(np.intersect1d(a,b))

[8]


In [ ]:
a=np.array([2,5,7,8,])
b=np.array([3,6,8,9,33])  #union(remove common ele and print a set display)
print(np.setdiff1d(a,b))

[2 5 7]


ROUNDING:

In [ ]:
a=np.trunc([-3.1666,3.6667])
print(a)

[-3.  3.]


In [ ]:
a=np.fix([-3.1666,3.6667])
print(a)

[-3.  3.]


In [ ]:
a=np.around([3.16636],4)
print(a)

[3.1664]




```
# This is formatted as code
```



In [ ]:
a=np.floor([-3.1666,3.6667])
print(a)

[-4.  3.]


In [ ]:
a=np.ceil([-3.1666,3.6667])
print(a)

[-3.  4.]


MORE FUNCTIONS:

In [ ]:
a=np.array([41666,3.6667,456,67,67,89]) #add the array
print(np.cumsum(a))

[41666.     41669.6667 42125.6667 42192.6667 42259.6667 42348.6667]


In [ ]:
a=np.array([34,34,67,78])     #multipulcation
print(np.cumprod(a))

[     34    1156   77452 6041256]


In [ ]:
print(np.gcd(38,78))
print(np.lcm(38,78))

2
1482


In [ ]:
a=np.array([34,78,45,67])
print(np.lcm.reduce(a))

1332630


In [ ]:
a=np.array([34,78,45,67])
print(np.gcd.reduce(a))

1


In [ ]:
a=np.array([[34,78],[45,67]])     #1/ad-bc(d-b)
print(np.linalg.inv(a))

[[-0.05438312  0.06331169]
 [ 0.03652597 -0.0275974 ]]


RANDOM:

In [ ]:
from numpy import random as rd

In [ ]:
a=rd.rand(10) #rand(n) #default limit is 0to 0.99
print(a)

[0.28461493 0.80012844 0.01037279 0.7572012  0.11267631 0.17897193
 0.92835116 0.90035822 0.67874412 0.12905329]


In [ ]:
a=rd.rand()
print(a)

0.027549049057238317


In [ ]:
a=rd.randint(50,size=(2,3)) #limit
print(a)

[[34 16 23]
 [22 25 26]]


In [ ]:
a=rd.randint(10)
print(a)

7


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])     #1x4,2x5,3x6=4+10+18=32
print(np.inner(a,b))

32


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])     #
print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])     #determined
print(np.cross(a,b))

[-3  6 -3]


ROUNDING: