In [ ]:
#variable
a=10
print("i am" ,a,"years old")

i am 10 years old


In [ ]:
#arithematic  oops interger variables
a=int(input("enter a value = "))
b=int(input("enter b value = "))
c=a+b
d=a-b
e=a*b
f=a%b
g=a/b
h=a**b
i=a//b
print("sum is:",c)
print("difference is:",d)
print("product is:",e)
print("quotient is:",f)
print("remainder is:",g)
print("power of is:",h)
print("floor division is:",i)

enter a value = 5
enter b value = 6
sum is: 11
difference is: -1
product is: 30
quotient is: 5
remainder is: 0.8333333333333334
power of is: 15625
floor division is: 0


In [ ]:
#problem statment
#take the salary from the user if the salary is more then 50,000 there is a 10% tax print his final salary
s=int(input("enter the salary:"))
if(s>50000):
  tax=(10/100)*s
  s=s-tax
  print(" final salary  is:",s)
else:
  print("no final salary is:",s)


KeyboardInterrupt: Interrupted by user

In [ ]:
#get the salary from the  user if salary is more then or equal to 50,000 apply 10% tax reduction if the salary is less then 50,000 appply 5% tax if the salary is more then70,000 apply 12% tax if salary exeste 1lk print ur promoted to next level
s=int(input("enter salary:"))
if(s<=50000):
  tax=(5/100)*s
  s=s-tax
  print("salary:",s)
elif(s>=50000 and s<=70000):
  tax=(10/100)*s
  s=s-tax
  print("salary:",s)
elif(s>70000 and s<=100000):
  tax=(12/100)*s
  s=s-tax
  print("salary is:",s)
else:
  print("promoted")




enter salary:1000001
promoted


In [ ]:
n=int(input("enter a number"))
for i in range(1,11):
  print(n,"*",i,"=",n*i)


enter a number5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
n=int(input("enter a number"))
i=1
while(i<=10):
  print(n,"*",i,"=",n*i)
  i=i+1

enter a number6
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60


In [ ]:
#list
l1=[1,"Kill",45,"chat",2.5,True]
for i in l1:
  print(i)

1
Kill
45
chat
2.5
True


In [ ]:
#list
l1=[1,"Kill",45,"chat",2.5,True]
for i in l1:
  print(i)

1
Kill
45
chat
2.5
True


In [ ]:
#mutable
l1.append("l love u")
print(l1)
l1.insert(3,"t")
print(l1)

[1, 'Kill', 45, 'u', 'u', 'chat', 'u', 2.5, True, 'appand', 'l love u', 'u', 'l love u', 'l love u', 'l love u', 'l love u', 'l love u']
[1, 'Kill', 45, 't', 'u', 'u', 'chat', 'u', 2.5, True, 'appand', 'l love u', 'u', 'l love u', 'l love u', 'l love u', 'l love u', 'l love u']


In [ ]:
#mutable
l0=["hello","hyy",45,67]
l0.append("hi")
print(l0)
l0.insert(3,"t")
print(l0)

['hello', 'hyy', 45, 67, 'hi']
['hello', 'hyy', 45, 't', 67, 'hi']


NameError: name 'popoy' is not defined

In [ ]:
print(l1)

['popoye', 'hi', 'popoye', 'hi', 'popoye', 'hi', 'popoye', 'hi']


In [ ]:
l2=["popoye","hi"]
l1.extend(l2)
print(l1)

['popoye', 'hi', 'popoye', 'hi', 'popoye', 'hi', 'popoye', 'hi']


In [ ]:

l1.pop(2)
print(l1)

['popoye', 'hi', 'hi', 'popoye', 'hi', 'popoye', 'hi']


In [ ]:
#pop
l=["hi",45,90]
l.pop(2)
print(l)


['hi', 45]


In [ ]:
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [ ]:
#remove
l=["hi",45]
l.remove('hi')
print(l)

[45]


In [ ]:
#prolem statments
#create a list of 10 integers ele and print their squares and saves these suares in new lists
l=[1,2,3,4,5,6,7,8,9,0]
s=[]
for i in l:
  s.append(i**2)
print(s)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 0]


In [ ]:

#relational operator
a=10
b=20
print(a!=b)

True


In [ ]:
a=10
b=10
print(a==b)

True


In [ ]:
a=10
b=10
print(a>b)
print(a<b)
print(a<=b)
print(a>=b)

False
False
True
True


In [ ]:
#logical operator
a=10
b=10
print(a>b)and(a<b)
print(a>b)or(a<b)

False
False


False

In [ ]:
#list coparision
lc=[1,2,3,4,5]
sc=[i*i for  i in lc]
print(sc)

[1, 4, 9, 16, 25]


In [ ]:
#list c
#newlist=[(st of if) if (cond) else (st of else) for ]
l1=[23,45,67,89]
res=[i*i if i>50 else 'x'for i in l1]
print(res)

['x', 'x', 4489, 7921]


In [ ]:
#take the salary from the user if the salary is less then 50k 10% tax other wise 15% tax
s=[450000,34555,34778]
l = [i-i*0.1 if i<500000 else i-i*0.15 for i in s]
print(l)

[405000.0, 31099.5, 31300.2]


In [ ]:
li=[1,2,3]
ss=[i**2 for i in li]
print(ss)

[1, 4, 9]


In [ ]:
#dictionary
dictname={123:'sriya',34:'yesh',56:'triveni',78:'ramya'}
print(dictname)

{123: 'sriya', 34: 'yesh', 56: 'triveni', 78: 'ramya'}


In [ ]:
#key
#values
#random name
print(dictname.keys())
print(dictname.values())
print(dictname[78])

dict_keys([123, 34, 56, 78])
dict_values(['sriya', 'yesh', 'triveni', 'ramya'])
ramya


In [ ]:
#random name sec count
dict1={"dept":"cse","details":{"year":"2","sec":"d","count":71}}
print("yearis:",dict1["details"]["year"])
print("countis:",dict1["details"]["count"])
print("sec:",dict1["details"]["sec"])


yearis: 2
countis: 71
sec: d


In [ ]:
idl=[32,45,67]
names=["joe","ramya","sriya"]
new_dict=(zip(idl,names))
for i in new_dict:
  print(new_dict)

In [ ]:
import numpy as np
a= np.array([1,2,3,4])#1dimention
print(a.ndim)
print(a.shape)

1
(4,)


In [ ]:
b= np.array([[1,2,3,4],[1,6,7,8]])#2dimention
print(b.ndim)
print(b.shape)

2
(2, 4)


In [ ]:
c= np.array([[[1,2,3,4],[1,6,7,8]],[[4,6,7,8],[3,5,7,8]]])#3dimention
print(c.ndim)
print(c.shape)

3
(2, 2, 4)


In [ ]:
a=np.arange(1,10,2)#start,stop,step
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all a numbers thet are divisable by 8 using array function b/w 1to1000
a=np.arange(8,1001,8)#8th table(start,stop,,step)
print(a)


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
a=np.linspace(12,34,12)#lower,upper,n(linspace:split a range into n numbers with comman differences)
print(a)

[12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.]


In [ ]:
studytuple and set(day1)
documen
qrcode


In [ ]:
a=np.eye(4)#to implementt identity matrix
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#create a tuple
tup=("hi","hello")
print(tup)

('hi', 'hello')


In [5]:
t=("hi","hello","min","max")
print(t[0])

hi


In [6]:
t=("hi","hello","min","max")
print(t[3])

max


In [7]:
t=("hi","hello","min","max")
print(len(t))

4


In [9]:
set={"hi","hello"}
set.remove("hi")
print(set)

{'hello'}


In [11]:
set={"hi","hello"}
print(set)

{'hello', 'hi'}
